"""Closed-loop C SIL with a separate circuit ODE checked against Python.

Not HIL. Datasheet anchors and Foster coefficients do not calibrate the full
electrical surrogate. PC timings do not qualify a real-time target.
"""
from pathlib import Path
import ctypes as ct, json, hashlib, time, platform, argparse, subprocess
import numpy as np
import scipy
import matplotlib.pyplot as plt
import plant_validation as p

ROOT=p.ROOT;BUILD=ROOT/'validation/sil';BUILD.mkdir(exist_ok=True)
SOURCE='https://www.infineon.com/dgdl/Infineon-IKx40N65H5-DS-v02_01-EN.pdf?fileId=db3a30433af5291e013afa8ba6fb6078'
MODEL=dict(device='IKW40N65H5',source=SOURCE,revision='2.1 (2015-05-06)',
 source_pages=dict(static_anchors=5,Foster_coefficients=12),
 transistor_R_K_W=[.08245484,.144197,.2151774,.1581708],
 transistor_tau_s=[7.3e-5,7e-4,.01235548,.08020881],
 diode_R_K_W=[.6701584,.775759,.3540826],diode_tau_s=[3.4e-4,4.7e-3,.04680901],
 transistor_static_anchor=dict(current_A=40,T_C=[25,125,175],voltage_V=[1.65,1.85,1.95],gate_V=15),
 diode_static_anchor=dict(current_A=20,T_C=[25,125,175],voltage_V=[1.45,1.40,1.40],gate_V=0),
 assumed_slopes_ohm=dict(transistor=.020,diode=.015),
 electrical_rule='Assumed affine current slopes; offsets chosen to reproduce static typical anchors; piecewise linear temperature interpolation at fixed slopes. Not a digitized full output curve or measured calibration.',
 boundary='Fixed case temperature, 25 or 75 C. Foster modal temperature rises; no shared dynamic case or ambient-temperature interpretation.',
 losses='Conduction only; switching energy, recovery, cross-coupling and parasitics excluded.',
 temperature_domain_C=[25,175])
TR=np.arange(24)%2==0
R=np.where(TR[:,None],np.array(MODEL['transistor_R_K_W']),np.r_[MODEL['diode_R_K_W'],0])
TAU=np.where(TR[:,None],np.array(MODEL['transistor_tau_s']),np.r_[MODEL['diode_tau_s'],1])
R0=np.where(TR,.020,.015)
A=p.incidence('Ttype')

def nominal(T,slopes=1.):
    T=np.asarray(T).reshape(-1)
    if T.min()<25-1e-9 or T.max()>175+1e-9:raise ValueError('Outside declared datasheet temperature domain')
    anchor=np.where(TR,np.interp(T,[25,125,175],[1.65,1.85,1.95]),np.interp(T,[25,125,175],[1.45,1.40,1.40]))
    r=R0*slopes
    return anchor-np.where(TR,40,20)*r,r

def prepare():
    X=np.load(ROOT/'data/separating_fixture.npz')['X'];_,s,v=np.linalg.svd(X,full_matrices=False)
    rank=int((s>1e-10).sum());assert rank==36
    basis=v[:rank].T
    l=np.zeros((2,50));l[0,[0,7]]=[1,-1];l[1,[24,30]]=[1,-1]
    defect=float(abs(l@basis@basis.T-l).max());assert defect<1e-12
    header='/* Independent separating-fixture quotient basis; generated by sil_validation.py --prepare. */\nstatic const double basis[50][36]={\n'
    header+=',\n'.join('{'+','.join(f'{x:.17g}' for x in row)+'}' for row in basis)+'\n};\n'
    (ROOT/'scripts/sil_basis.h').write_text(header,encoding='ascii')
    (ROOT/'data/sil_model.json').write_text(json.dumps(MODEL,indent=2))
    return defect

DP=ct.POINTER(ct.c_double);IP=ct.POINTER(ct.c_int)
def dp(a):return np.ascontiguousarray(a,dtype=np.float64).ctypes.data_as(DP)
def ip(a):return np.ascontiguousarray(a,dtype=np.int32).ctypes.data_as(IP)

def load():
    dll=ct.CDLL(str(BUILD/'sil_core.dll'))
    dll.sil_control.argtypes=[ct.c_double,DP,IP,IP];dll.sil_control.restype=None
    dll.sil_observe.argtypes=[ct.c_double,DP,DP,IP,IP,DP,DP,ct.c_double,DP,DP];dll.sil_observe.restype=ct.c_int
    dll.sil_fit.argtypes=[ct.c_int,DP,DP,IP,DP,DP];dll.sil_fit.restype=ct.c_int
    dll.sil_timing.argtypes=[ct.c_int,DP];dll.sil_timing.restype=None
    dll.sil_advance.argtypes=[ct.c_double,DP,IP,ct.c_double,ct.c_double,ct.c_int,ct.c_double];dll.sil_advance.restype=None
    return dll

def controller_py(t,sense,old):
    cand=p.STATES[np.all(abs(p.STATES-old)<=1,axis=1)]
    v,r=nominal(np.full(24,25));ids=p.path_ids(cand,sense,'Ttype')
    drop=np.sign(sense)*(A@v[:8])[ids]+sense*(A@r[:8])[ids]
    pred=sense+.025*((150*cand-drop-p.emf(t,p.CFG))@p.P0-.25*sense)
    cost=np.sum((pred-p.reference(t+50e-6))**2,axis=1)+.005*np.sum((cand-old)**2,axis=1)
    return cand[np.argmin(cost)]

def run(dll,N,case,aged,seed=20261012,replay=None,refine=4,native=True):
    rng=np.random.default_rng(seed);noise=rng.normal(0,case.get('noise',0),(N+1,3))
    states=np.zeros((N,3),np.int32);curr=np.zeros((N+1,3));sensed=curr.copy()
    thermal=np.zeros((N+1,24));thermal[0]=case['Tcase'];old=np.zeros(3,np.int32)
    state=np.zeros(99);capture=np.zeros(3);history=np.zeros((N+1,3))
    dv=np.zeros(24);dr=dv.copy()
    if aged:dv[0]=.05;dr[0]=.0002
    offset=np.array(case.get('skew_us',[0,0,0]))*1e-6
    delay=case.get('actuation_us',0)*1e-6;controller_mismatch=0
    def deriv(t,x,q):
        i=x[:3];T=case['Tcase']+x[3:].reshape(24,4).sum(axis=1)
        v,r=nominal(T,case.get('slope_factor',1.));v+=dv;r+=dr
        active=A[p.path_ids(q,i,'Ttype')]
        drop=(active*(v.reshape(3,8)+abs(i[:,None])*r.reshape(3,8))).sum(axis=1)
        pole=150*q-np.sign(i)*drop
        di=(p.P0@(pole-p.emf(t,p.CFG))-.25*i)/.002
        power=(active*(abs(i[:,None])*v.reshape(3,8)+i[:,None]**2*r.reshape(3,8))).ravel()
        modal=x[3:].reshape(24,4)
        return np.r_[di,((R*power[:,None]-modal)/TAU).ravel()]
    def step(t,x,q,h,depth=0):
        k1=deriv(t,x,q);s2=x+h*k1/2;k2=deriv(t+h/2,s2,q)
        s3=x+h*k2/2;k3=deriv(t+h/2,s3,q);s4=x+h*k3;k4=deriv(t+h,s4,q)
        end=x+h*(k1+2*k2+2*k3+k4)/6
        sign=np.sign(np.stack([x[:3],s2[:3],s3[:3],s4[:3],end[:3]]))
        if depth<8 and np.any(sign.min(axis=0)!=sign.max(axis=0)):
            return step(t+h/2,step(t,x,q,h/2,depth+1),q,h/2,depth+1)
        return end
    start=time.perf_counter()
    for k in range(N):
        sense=capture+noise[k]
        bits=case.get('bits',0)
        if bits:
            lsb=64/2**bits;sense=np.clip(np.rint(sense/lsb),-2**(bits-1),2**(bits-1)-1)*lsb
        sensed[k]=sense;history[k]=sense
        control=history[max(0,k-case.get('input_delay',0))]
        q=np.zeros(3,np.int32)
        if replay is None:
            dll.sil_control(k*50e-6,dp(control),ip(old),ip(q))
            if case['name']=='clean25':controller_mismatch+=int(np.any(q!=controller_py(k*50e-6,control,old)))
        else:q[:]=replay[k]
        states[k]=q
        free=np.where(state[:3]>=0,np.minimum(old,q),np.maximum(old,q))
        boundaries=[(old,delay),(free,1e-6),(q,49e-6-delay)];elapsed=0
        capture=state[:3].copy()
        sample_at=50e-6-offset
        for lev,duration in boundaries:
            if duration<=0:continue
            checkpoints=np.unique(np.r_[elapsed+np.linspace(0,duration,refine+1)[1:],sample_at[(sample_at>elapsed+1e-15)&(sample_at<=elapsed+duration+1e-15)]])
            for checkpoint in checkpoints:
                h=checkpoint-elapsed
                if h>1e-15:
                    if native:dll.sil_advance(k*50e-6+elapsed,dp(state),ip(lev),h,case['Tcase'],int(aged),case.get('slope_factor',1.))
                    else:state=step(k*50e-6+elapsed,state,lev,h)
                elapsed=checkpoint
                for j in range(3):
                    if abs(checkpoint-sample_at[j])<1e-14:capture[j]=state[j]
        curr[k+1]=state[:3];thermal[k+1]=case['Tcase']+state[3:].reshape(24,4).sum(axis=1)
        old=q.copy()
    sense=capture+noise[-1]
    if case.get('bits',0):
        lsb=64/2**case['bits'];sense=np.clip(np.rint(sense/lsb),-2**(case['bits']-1),2**(case['bits']-1)-1)*lsb
    sensed[-1]=sense
    assert np.max(abs(curr))<31.99,'ADC range violated'
    return dict(current=curr,sensed=sensed,states=states,junction=thermal,case=case,aged=aged,N=N,controller_mismatches=controller_mismatch,elapsed_s=time.perf_counter()-start)

def analyze(dll,rec,compensate=True,known_delay=None,temperature_offset=0.):
    N=rec['N'];X=np.zeros((N,2,50));y=np.zeros((N,2));keep=np.zeros(N,np.int32)
    old=np.vstack([np.zeros(3,np.int32),rec['states'][:-1]])
    for k in range(N):
        T=(rec['junction'][k]+rec['junction'][k+1])/2 if compensate else np.full(24,25)
        if compensate:T=T+temperature_offset
        v,r=nominal(T)
        keep[k]=dll.sil_observe(k*50e-6,dp(rec['sensed'][k]),dp(rec['sensed'][k+1]),ip(rec['states'][k]),ip(old[k]),dp(v),dp(r),known_delay or 0.,dp(X[k]),dp(y[k]))
    target=np.zeros(2);diag=np.zeros(4);start=time.perf_counter()
    status=dll.sil_fit(N,dp(X),dp(y),ip(keep),dp(target),dp(diag));elapsed=time.perf_counter()-start
    assert status==0,(status,diag)
    estimate,se,rank,defect,_,details=p.fit(X.reshape(-1,50),y.ravel(),keep=keep.astype(bool))
    difference=abs(target-estimate);assert difference.max()<1e-8,(difference,target,estimate)
    assert rank==36 and defect.max()<1e-7
    return dict(estimate=target.tolist(),nominal_SE=se.tolist(),rank=rank,retained=int(diag[0]),C_python_difference=difference.tolist(),target_defect=defect.tolist(),fit_elapsed_s=elapsed,QR_min_scaled_diagonal=float(diag[2])),(X,y,keep)

def operator_check(dll,rec):
    N=rec['N'];current=rec['sensed'];mid=(current[:-1]+current[1:])/2;q=rec['states']
    old=np.vstack([np.zeros(3,np.int32),q[:-1]]);free=np.where(mid>=0,np.minimum(old,q),np.maximum(old,q))
    Bleg=.04*A[p.path_ids(old,mid,'Ttype')]+.02*A[p.path_ids(free,mid,'Ttype')]+.94*A[p.path_ids(q,mid,'Ttype')]
    B=np.zeros((N,3,24))
    for phase in range(3):B[:,phase,8*phase:8*(phase+1)]=Bleg[:,phase]
    z=np.sign(mid);n=abs(q-free);T=(rec['junction'][:-1]+rec['junction'][1:])/2
    v=np.stack([nominal(temp)[0] for temp in T]).reshape(N,3,8);r=np.tile(R0,(N,1)).reshape(N,3,8)
    nominal_pole=150*(.04*old+.02*free+.94*q)-z*np.sum(Bleg*v,axis=2)-mid*np.sum(Bleg*r,axis=2)
    emf=20*np.sin(2*np.pi*25*(np.arange(N)[:,None]+.5)*50e-6+p.SHIFT)
    yp=(40*np.diff(current,axis=0)-nominal_pole+.25*mid+emf)@p.C.T
    xp=np.concatenate([-np.einsum('ab,kb,kbd->kad',p.C,z,B),-np.einsum('ab,kb,kbd->kad',p.C,mid,B),np.stack([-(n*z)@p.C.T,-mid@p.C.T],axis=2)],axis=2)
    keep=np.all((abs(current[:-1])>.5)&(abs(current[1:])>.5)&(current[:-1]*current[1:]>0),axis=1)
    xc=np.zeros_like(xp);yc=np.zeros_like(yp);kc=np.zeros(N,np.int32)
    for k in range(N):
        vv,rr=nominal(T[k]);kc[k]=dll.sil_observe(k*50e-6,dp(current[k]),dp(current[k+1]),ip(q[k]),ip(old[k]),dp(vv),dp(rr),2e-6,dp(xc[k]),dp(yc[k]))
    np.testing.assert_array_equal(kc.astype(bool),keep)
    dx=float(abs(xc[keep]-xp[keep]).max());dy=float(abs(yc[keep]-yp[keep]).max());assert dx<1e-12 and dy<1e-11,(dx,dy)
    target=np.zeros(2);diag=np.zeros(4);short_status=dll.sil_fit(N,dp(xc),dp(yc),ip(kc),dp(target),dp(diag))
    assert short_status<0,'A short physical window with missing sign/path support must be rejected'
    return dict(operator_X_difference=dx,operator_y_difference=dy,operator_retention_match=True,short_physical_window_status=short_status,short_physical_window_periods=N)

def check(dll):
    rng=np.random.default_rng(20261013);mismatch=0
    for k in range(2000):
        sense=rng.uniform(-25,25,3);old=p.STATES[rng.integers(27)].astype(np.int32);q=np.zeros(3,np.int32);t=rng.uniform(0,1)
        dll.sil_control(t,dp(sense),ip(old),ip(q));mismatch+=int(np.any(q!=controller_py(t,sense,old)))
    assert mismatch==0
    fixture=dict(name='plant_parity',Tcase=75,actuation_us=2,skew_us=[0,1,2])
    cpp=run(dll,128,fixture,True);py=run(dll,128,fixture,True,replay=cpp['states'],native=False)
    parity_i=float(abs(cpp['current']-py['current']).max());parity_T=float(abs(cpp['junction']-py['junction']).max())
    # Zero-current commutation branches are sensitive to roundoff in P0 versus
    # explicit neutral elimination; require agreement well below sensor noise.
    assert parity_i<1e-6 and parity_T<1e-6,(parity_i,parity_T)
    operator=operator_check(dll,cpp)
    # Independent analytic Foster step response, not the trajectory integrator.
    t=np.geomspace(1e-6,1,300);z=(R[:,:,None]*(1-np.exp(-t/TAU[:,:,None]))).sum(axis=1)
    assert np.all(np.diff(z,axis=1)>=0);np.testing.assert_allclose(R.sum(axis=1),np.where(TR,.6,1.8),atol=1e-12)
    v,r=nominal(np.full(24,25));np.testing.assert_allclose((v+np.where(TR,40,20)*r)[[0,1]],[1.65,1.45],atol=1e-14)
    # A nonseparating record must be rejected rather than assigned a health vector.
    X=np.zeros((50,2,50));y=np.zeros((50,2));keep=np.ones(50,np.int32);out=np.zeros(2);diag=np.zeros(4)
    status=dll.sil_fit(50,dp(X),dp(y),ip(keep),dp(out),dp(diag));assert status<0
    return dict(controller_random_vectors=2000,controller_mismatches=mismatch,nonseparating_status=status,thermal_Rsum_verified=True,static_anchors_verified=True,independent_plant_C_Python_current_difference_A=parity_i,independent_plant_C_Python_temperature_difference_K=parity_T,**operator)

def render(result,records):
    fig,ax=plt.subplots(1,2,figsize=(7.2,3.2),layout='constrained')
    t=np.geomspace(1e-6,1,300)
    for j,label in [(0,'IGBT'),(1,'Diode')]:ax[0].loglog(t,(R[j,:,None]*(1-np.exp(-t/TAU[j,:,None]))).sum(axis=0),label=label)
    ax[0].set(xlabel='Time (s)',ylabel='Junction-to-case impedance (K/W)',title='Datasheet Foster coefficients');ax[0].legend(fontsize=8);ax[0].grid(alpha=.2)
    rec=records['clean75_aged'];t=np.arange(rec['N']+1)*50e-6
    for j,label in [(0,'S1a'),(6,'S4a'),(7,'D4a')]:ax[1].plot(t,rec['junction'][:,j],label=label)
    ax[1].axhline(75,lw=.8,ls='--',color='gray');ax[1].set(xlabel='Time (s)',ylabel='Model junction temperature (C)',title='Fixed 75 C case, conduction heat');ax[1].legend(fontsize=8);ax[1].grid(alpha=.2);p.save(fig,'sil_thermal')
    rows=result['conditions'];fig,axes=plt.subplots(2,1,sharex=True,figsize=(7.2,4.3),layout='constrained')
    for j,ax in enumerate(axes):
        ax.plot(np.arange(len(rows)),[1000*r['contrast'][j] for r in rows],'o');ax.scatter(np.arange(len(rows)),[1000*r.get('truth',[.05,.0002])[j] for r in rows],marker='x',color='gray')
        ax.set_xticks(range(len(rows)),[r['label'] for r in rows],fontsize=7,rotation=30,ha='right');ax.set(ylabel='Threshold contrast (mV)' if j==0 else r'Resistance contrast (m$\Omega$)');ax.grid(alpha=.2)
        if j==1:ax.set_yscale('symlog',linthresh=.25);ax.set_yticks([-1,0,.2,1,10,30],['-1','0','0.2','1','10','30']);ax.set_ylim(-1.5,45)
    p.save(fig,'sil_contrasts')
    table=['\\begin{table}[t]\\centering\\small','\\caption{Closed-loop compiled-C SIL. Healthy and injected records are regenerated per condition; same-condition references are used except for the declared healthy-warming comparison (truth zero). Injected change: 50 mV and 0.2 m$\\Omega$.}\\label{tab:sil}',r'\begin{tabular}{@{}lrr@{}}\toprule Condition&$\widehat h_v$ (mV)&$\widehat h_r$ (m$\Omega$)\\\midrule']
    for row in rows:table.append(row['tex_label']+'&'+'&'.join(f'{1000*x:.3f}' for x in row['contrast'])+r'\\')
    table += [r'\bottomrule\end{tabular}\end{table}']
    worst=np.max([r['C_python_difference'] for r in result['records'].values()],axis=0)
    timing=result['timing']
    table.append(f'The C and Python GLS target estimates agree within {worst[0]:.2g} V and {worst[1]:.2g} $\\Omega$ over all reported records. Each accepted operator has rank 36; retained-period counts range from {min(r["retained"] for r in result["records"].values())} to {max(r["retained"] for r in result["records"].values())}.')
    table.append(f'On the recorded PC, {timing["repeats"]} native controller calls have median {timing["median_us"]:.2f} $\\mu$s, 95th percentile {timing["p95_us"]:.2f} $\\mu$s and observed maximum {timing["max_observed_us"]/1000:.2f} ms. Full-window C GLS elapsed time ranges from {1000*timing["fit_min_s"]:.1f} to {1000*timing["fit_max_s"]:.1f} ms. The host maximum exceeds the nominal control period; simulation advances algorithmic time offline. These are host measurements, not worst-case execution-time bounds or target deadline qualification.')
    (ROOT/'sil_computed_summary.tex').write_text('\n'.join(table)+'\n')
    refinement=result['refinement'];mc=result['feedback_MC'];check=result['checks'];audit=[]
    audit.append(f'The 128-period independent plant comparison differs by at most {1e6*check["independent_plant_C_Python_current_difference_A"]:.3f} $\\mu$A and {1e6*check["independent_plant_C_Python_temperature_difference_K"]:.3f} $\\mu$K. The {check["controller_random_vectors"]}-vector controller check and the clean-record controller comparison select identical gates. The nonseparating test is rejected.')
    audit.append(f'Full-window fixed-gate refinement changes endpoint currents by at most {1e6*refinement["max_current_difference_A"]:.2f} $\\mu$A and junction temperatures by {1e6*refinement["max_temperature_difference_K"]:.2f} $\\mu$K; the target changes are {1e9*refinement["target_difference"][0]:.3f} nV and {1e9*refinement["target_difference"][1]:.3f} n$\\Omega$.')
    audit.append(f'The five 12-bit/noise feedback realizations produce {mc["distinct_aged_gate_records"]} distinct injected gate records. Their mean contrast is ({1000*mc["mean"][0]:.3f} mV, {1000*mc["mean"][1]:.3f} m$\\Omega$), with between-realization standard deviations ({1000*mc["SD"][0]:.3f} mV, {1000*mc["SD"][1]:.3f} m$\\Omega$). These empirical dispersions are not conditional Gaussian bounds.')
    if 'electrical_slope_sensitivity' in result:
        audit.append('With plant current slopes changed by $-25\\%$ and $+25\\%$, while preserving the source anchors, the contrast estimates are '+ ' and '.join(f'({1000*r["contrast"][0]:.3f} mV, {1000*r["contrast"][1]:.3f} m$\\Omega$)' for r in result['electrical_slope_sensitivity'])+'. This is a declared model-sensitivity intervention, not a measured uncertainty bound.')
    (ROOT/'sil_audit_summary.tex').write_text('\n\n'.join(audit)+'\n')

def main(args):
    if args.prepare:print('basis_defect',prepare());return
    if args.extend:
        dll=load();result=json.loads((ROOT/'data/sil_results.json').read_text());result['checks']=check(dll);rows=[]
        for factor in [.75,1.25]:
            case=dict(name='slope_sensitivity',Tcase=75,slope_factor=factor);pair=[]
            for aged in [False,True]:
                rec=run(dll,result['periods'],case,aged);res,_=analyze(dll,rec);pair.append(res['estimate'])
                np.savez_compressed(ROOT/'data'/f'sil_slope{factor}_{"aged" if aged else "healthy"}.npz',**{k:rec[k] for k in ['current','sensed','states','junction']})
            rows.append(dict(physical_slope_factor=factor,static_anchors_preserved=True,contrast=(np.array(pair[1])-pair[0]).tolist()))
            print('SIL_SLOPE_SENSITIVITY',rows[-1],flush=True)
        result['electrical_slope_sensitivity']=rows
        for name in result['hashes']:result['hashes'][name]=hashlib.sha256((ROOT/name).read_bytes()).hexdigest()
        (ROOT/'data/sil_results.json').write_text(json.dumps(result,indent=2))
        z=np.load(ROOT/'data/sil_clean75_aged.npz');rec={k:z[k] for k in ['current','sensed','states','junction']};rec['N']=result['periods']
        render(result,{'clean75_aged':rec});return
    dll=load();checks=check(dll);records={};results={};rows=[]
    cases=[dict(name='clean25',Tcase=25,label='Clean 25 C',tex_label='Ideal sensing, 25 $^\\circ$C case'),
           dict(name='clean75',Tcase=75,label='Clean 75 C',tex_label='Ideal sensing, 75 $^\\circ$C case'),
           dict(name='adc16',Tcase=75,bits=16,noise=.002,label='16-bit + noise',tex_label='16-bit ADC + 2 mA noise'),
           dict(name='adc12',Tcase=75,bits=12,noise=.002,label='12-bit + noise',tex_label='12-bit ADC + 2 mA noise'),
           dict(name='skew',Tcase=75,bits=16,noise=.002,skew_us=[0,1,2],label='ADC + skew',tex_label='16-bit ADC/noise + 0/1/2 $\\mu$s skew'),
           dict(name='inputdelay',Tcase=75,bits=16,noise=.002,input_delay=1,label='ADC + input delay',tex_label='16-bit ADC/noise + one-period input delay'),
           dict(name='actdelay',Tcase=75,actuation_us=2,label='Gate delay, unknown',tex_label='Extra 2 $\\mu$s gate delay, undeclared'),
           dict(name='combined',Tcase=75,bits=12,noise=.002,input_delay=1,skew_us=[0,1,2],actuation_us=2,label='Combined',tex_label='12-bit/noise + skew + input/gate delay')]
    if args.smoke:cases=cases[:1]
    for case in cases:
        estimates=[]
        for aged in [False,True]:
            tag=case['name']+('_aged' if aged else '_healthy');cache=ROOT/'data'/('sil_'+tag+'.npz')
            if args.reuse and cache.exists():
                z=np.load(cache);rec={k:z[k] for k in ['current','sensed','states','junction']};rec.update(N=args.periods,case=case,aged=aged,controller_mismatches=0)
                assert len(rec['states'])==args.periods
            else:
                rec=run(dll,args.periods,case,aged)
                np.savez_compressed(cache,**{k:rec[k] for k in ['current','sensed','states','junction']})
            assert rec['controller_mismatches']==0
            res,_=analyze(dll,rec);records[tag]=rec;results[tag]=res;estimates.append(res['estimate'])
            print('SIL_RECORD',tag,json.dumps(res),flush=True)
        rows.append({**case,**dict(contrast=(np.array(estimates[1])-estimates[0]).tolist())})
    if args.smoke:return
    # Same simulated records, explicitly separate compensation interventions.
    for tag,comp,delay,label,tex in [
        ('clean75',False,0,'75 C, no T correction','75 $^\\circ$C case, no thermal correction'),
        ('actdelay',True,2e-6,'Gate delay, recorded','Extra 2 $\\mu$s gate delay, recorded')]:
        estimates=[]
        for aged in [False,True]:
            rec=records[tag+('_aged' if aged else '_healthy')];res,_=analyze(dll,rec,comp,delay)
            results[tag+('_aged' if aged else '_healthy')+('_noT' if not comp else '_recorded')]=res;estimates.append(res['estimate'])
        rows.append(dict(name=tag+('_noT' if not comp else '_recorded'),label=label,tex_label=tex,contrast=(np.array(estimates[1])-estimates[0]).tolist()))
    # Thermal calibration perturbation changes only the injected record.
    offset_result,_=analyze(dll,records['clean75_aged'],temperature_offset=2.)
    results['clean75_aged_offset2K']=offset_result
    rows.append(dict(name='offset2K',label='Junction offset +2 K',tex_label='Injected-record junction offset +2 K',contrast=(np.array(offset_result['estimate'])-results['clean75_healthy']['estimate']).tolist()))
    hot_noT,_=analyze(dll,records['clean75_healthy'],False);cold_noT,_=analyze(dll,records['clean25_healthy'],False)
    rows.append(dict(name='warming_noT',label='Healthy warming, no T',tex_label='Healthy 25-to-75 $^\\circ$C warming, no correction',truth=[0.,0.],contrast=(np.array(hot_noT['estimate'])-cold_noT['estimate']).tolist()))
    rows.append(dict(name='warming_oracle',label='Healthy warming, oracle T',tex_label='Healthy warming, oracle junction correction',truth=[0.,0.],contrast=(np.array(results['clean75_healthy']['estimate'])-results['clean25_healthy']['estimate']).tolist()))
    # Regenerate feedback, switching and plant for five independent noise seeds.
    ensemble=[];adc_case=next(c for c in cases if c['name']=='adc12');gate_hashes=[]
    ensemble.append(next(row['contrast'] for row in rows if row['name']=='adc12'))
    gate_hashes.append(hashlib.sha256(records['adc12_aged']['states'].tobytes()).hexdigest())
    for seed in range(20261013,20261017):
        pair=[]
        for aged in [False,True]:
            rec=run(dll,args.periods,adc_case,aged,seed=seed);res,_=analyze(dll,rec);pair.append(res['estimate'])
            np.savez_compressed(ROOT/'data'/f'sil_adc12_seed{seed}_{"aged" if aged else "healthy"}.npz',**{k:rec[k] for k in ['current','sensed','states','junction']})
            if aged:gate_hashes.append(hashlib.sha256(rec['states'].tobytes()).hexdigest())
        contrast=(np.array(pair[1])-pair[0]).tolist();ensemble.append(contrast);print('SIL_FEEDBACK_TRIAL',seed,contrast,flush=True)
    ens=np.array(ensemble)
    feedback_MC=dict(trials=5,seeds=list(range(20261012,20261017)),contrasts=ensemble,mean=ens.mean(axis=0).tolist(),SD=ens.std(axis=0,ddof=1).tolist(),RMSE=np.sqrt(np.mean((ens-[.05,.0002])**2,axis=0)).tolist(),distinct_aged_gate_records=len(set(gate_hashes)),scope='Five exploratory closed-loop feedback realizations, common random numbers within each healthy/aged pair; insufficient for confidence-coverage claims')
    assert feedback_MC['distinct_aged_gate_records']>1
    slope_sensitivity=[]
    for factor in [.75,1.25]:
        case=dict(name='slope_sensitivity',Tcase=75,slope_factor=factor);pair=[]
        for aged in [False,True]:
            rec=run(dll,args.periods,case,aged);res,_=analyze(dll,rec);pair.append(res['estimate'])
            np.savez_compressed(ROOT/'data'/f'sil_slope{factor}_{"aged" if aged else "healthy"}.npz',**{k:rec[k] for k in ['current','sensed','states','junction']})
        slope_sensitivity.append(dict(physical_slope_factor=factor,static_anchors_preserved=True,contrast=(np.array(pair[1])-pair[0]).tolist()))
        print('SIL_SLOPE_SENSITIVITY',slope_sensitivity[-1],flush=True)
    # Fixed-gate refinement of the entire electrothermal SIL window.
    rec=records['clean75_aged'];fine=run(dll,args.periods,rec['case'],True,replay=rec['states'],refine=8)
    np.savez_compressed(ROOT/'data/sil_clean75_aged_refine8.npz',**{k:fine[k] for k in ['current','sensed','states','junction']})
    fresult,_=analyze(dll,fine)
    refinement=dict(scope='Full window, fixed recorded gates; 4 versus 8 substeps per switching segment',periods=args.periods,
        max_current_difference_A=float(abs(fine['current']-rec['current']).max()),max_temperature_difference_K=float(abs(fine['junction']-rec['junction']).max()),
        target_difference=(np.array(fresult['estimate'])-results['clean75_aged']['estimate']).tolist())
    times=np.zeros(10000);dll.sil_timing(len(times),dp(times))
    fit_times=[x['fit_elapsed_s'] for x in results.values()]
    timing=dict(repeats=len(times),median_us=float(np.median(times)),p95_us=float(np.percentile(times,95)),max_observed_us=float(times.max()),fit_min_s=min(fit_times),fit_max_s=max(fit_times),scope='PC only; native QPC wall timing, single-thread process; no WCET, MCU or HIL timing claim')
    result=dict(evidence_kind='closed_loop_software_in_the_loop',hardware_validation_performed=False,periods=args.periods,Ts_s=50e-6,
        model=MODEL,seed=20261012,paired_noise_rule='Common random numbers in each healthy/injected pair, independently regenerated feedback and plant; one realization per condition, not population confidence coverage',
        sensing='Three independently quantized channels, bipolar [-32,32) A; per-channel 2 mA Gaussian noise before ADC; backward sampling offsets; no projection of measured currents',
        conditions=rows,records=results,checks=checks,feedback_MC=feedback_MC,electrical_slope_sensitivity=slope_sensitivity,refinement=refinement,timing=timing,
        host=dict(platform=platform.platform(),processor=platform.processor(),python=platform.python_version(),numpy=np.__version__,scipy=scipy.__version__),
        hashes={f.relative_to(ROOT).as_posix():hashlib.sha256(f.read_bytes()).hexdigest() for f in [ROOT/'scripts/sil_core.c',ROOT/'scripts/sil_plant.c',ROOT/'scripts/sil_basis.h',BUILD/'sil_core.dll',ROOT/'scripts/sil_validation.py']})
    (ROOT/'data/sil_results.json').write_text(json.dumps(result,indent=2));render(result,records)
    print('SIL_COMPLETE',json.dumps(dict(refinement=refinement,timing=timing,checks=checks)),flush=True)

if __name__=='__main__':
    parser=argparse.ArgumentParser();parser.add_argument('--prepare',action='store_true');parser.add_argument('--smoke',action='store_true');parser.add_argument('--reuse',action='store_true');parser.add_argument('--extend',action='store_true');parser.add_argument('--periods',type=int,default=4096);main(parser.parse_args())
